version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  backend:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      POSTGRES_URI: postgres://postgres:postgres@postgres:5432/library
    