name: CI/CD Pipeline

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_ECR_REGISTRY: 940878291215.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Build Backend
        run: |
          cd backend
          npm install --omit=dev
          npm run build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install and run tests
        run: |
          cd backend
          npm install
          npm test
  
  test-e2e:
    name: Test e2e
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install and run E2E tests
        run: |
          cd backend
          npm install
          npm run test:e2e

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: [build, test, test-e2e]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ env.AWS_DEFAULT_REGION }}
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build and Push Backend Docker image
        env:
          AWS_ECR_REPOSITORY: backend
        run: |
          cd backend
          docker build -t $AWS_ECR_REGISTRY/$AWS_ECR_REPOSITORY:latest .
          docker push $AWS_ECR_REGISTRY/$AWS_ECR_REPOSITORY:latest
